fix(client): Prevent disposing of the HttpMessageHandler in CamundaCoudTokenProvider
zeebe-io/zeebe-client-csharp pull request #222
Opened 2021-02-22 14:36 UTC by terjeinnerdal

Creates the HttpClient in CamundaCloudTokenProvider constructor. Added CamundaCloudTokenProvider.SetHttpMessageHandler method to set the HttpMessageHandler for testing which will create a new HttpClient.

closes #218

2021-02-23 06:58 UTC, Zelldon commented
Hey @terjeinnerdal thanks for fixing this. Could we add a separate test which fails before and now succeeds with the change?

2021-02-23 08:39 UTC, terjeinnerdal commented
Yes, that sounds like a good idea. I'll see if I can find the time today.

2021-02-24 09:21 UTC, terjeinnerdal commented
I've included a test now, but the continuous-integration check fails on the integration tests. It shows the following warning:
"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
TearDown failed for test fixture Client.IntegrationTests.WorkflowInstanceTest
Docker.DotNet.DockerContainerNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: camunda/zeebe:0.23.0"}"

2021-02-26 19:32 UTC, Zelldon requested changes
Thanks for the fix and the additional test :+1: I think we can simplify the test and then we can merge it :)

2021-02-26 19:32 UTC, Zelldon commented on Client.UnitTests/CamundaCloudTokenProviderTest.cs
> +            var firstToken = await TokenProvider.GetAccessTokenForRequestAsync();
```suggestion
           await TokenProvider.GetAccessTokenForRequestAsync();
```

2021-02-26 19:32 UTC, Zelldon commented on Client.UnitTests/CamundaCloudTokenProviderTest.cs
> +            await File.WriteAllTextAsync(tokenFile, "FILE_TOKEN");
```suggestion
```

2021-02-26 19:32 UTC, Zelldon commented on Client.UnitTests/CamundaCloudTokenProviderTest.cs
> +            Token = "SECOND_TOKEN";
```suggestion
```

2021-02-28 10:35 UTC, Zelldon commented
Thank you very much for your contribution @terjeinnerdal I created a separate PR to do the clean up for you and to merge it with the latest changes. https://github.com/zeebe-io/zeebe-client-csharp/pull/235

2021-02-28 10:43 UTC, closed without merging